nginx:
  image:
    repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-nginx

portal:
  image:
    repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-portal

core:
  image:
    repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-core

jobservice:
  image:
    repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-jobservice

registry:
  registry:
    image:
      repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-registry
  controller:
    image:
      repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-registryctl

trivy:
  image:
    repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-trivy-adapter

notary:
  server:
    image:
      repository: goharbor/notary-server-photon
  signer:
    image:
      repository: goharbor/notary-signer-photon

database:
  internal:
    image:
      repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-db

redis:
  internal:
    image:
      repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-redis

tests:
  api:
    image:
      repository: registry.suse.de/devel/caps/registry/containers/registry/harbor-test
    dind:
      image:
        repository: registry.suse.de/devel/caps/registry/containers/registry/docker-dind
